/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.bindery = {
    attach: function attach(context) {
      $(window).on('load', function () {
        if ($(".node--type-books").length && !$(".📖-root").length) {
          Bindery.makeBook({ content: ".node--type-books" });
        }
      });
    }
  };
})(jQuery, Drupal);