<?php

/**
 * @file
 * Contains bind_tweaks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bind_tweaks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bind_tweaks module.
    case 'help.page.bind_tweaks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Binding tweaks') . '</p>';
      return $output;

    default:
  }
}
